version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || true

  pre_build:
    commands:
      - echo Running tests...
      - pytest test_app.py

  build:
    commands:
      - echo Building the application...
      - mkdir -p build
      - cp app.py build/

artifacts:
  files:
    - build/*
